In [1]:
import neptune
import pandas as pd
import numpy as np

# Edit run meta info

In [2]:
# # Reopen by run ID (from sys/id)
# run = neptune.init_run(
#     with_id="DNAT-443",       # e.g. your run id
#     project="amar-mesic/dna-thesis",
#     mode="sync",         # important, otherwise it's read-only
#     api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJkOTQ1Njc4MC0yOTcyLTRlMmQtYTMwMy0xOGYxZTAwMmIzZGUifQ==",
# )

# # Add or overwrite metadata
# run["meta/experiment"] = "SPS"
# # run["meta/model"] = "Amar-DNANet_Lite"
# # run["meta/dataset"] = "proved_it"
# # run["meta/seed"] = 43
# # run["meta/fold"] = 1

# # Add tags too (handy in UI)
# # run["sys/tags"].add(["exp:Synth_data-Genotype_aware-SPS", "model:Amar-DNANet_Lite", "dataset:proved_it", "seed:43", "fold:1"])

# # Always stop after edits
# run.stop()

In [3]:
project = "amar-mesic/dna-thesis"
api_token = "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJkOTQ1Njc4MC0yOTcyLTRlMmQtYTMwMy0xOGYxZTAwMmIzZGUifQ=="

# for run_num in range(551, 601):  # 601 because range is exclusive at the end
#     run_id = f"DNAT-{run_num}"
#     run = neptune.init_run(
#         with_id=run_id,
#         project=project,
#         mode="sync",
#         api_token=api_token,
#     )
#     name = run["sys/name"].fetch()
#     if "对数" in name:
#         run["meta/experiment"] = "Genotype_aware-SPS-Standard-DRC"
#         print(f"{run_id}: Set to Genotype_aware-SPS-Standard-DRC")
#     elif "标准化" in name:
#         run["meta/experiment"] = "Genotype_aware-SPS-Standard"
#         print(f"{run_id}: Set to Genotype_aware-SPS-Standard")
#     else:
#         print(f"{run_id}: No match, not changed")
#     run.stop()

# for run_num in range(613, 646):  # Adjust 1000 to the latest run if needed
#     run_id = f"DNAT-{run_num}"
#     try:
#         run = neptune.init_run(
#             with_id=run_id,
#             project=project,
#             mode="sync",
#             api_token=api_token,
#         )
#         run["meta/experiment"] = "Synth_data-Genotype_aware-SPS"
#         print(f"{run_id}: Set to Synth_data-Genotype_aware-SPS")
#         run.stop()
#     except Exception as e:
#         print(f"{run_id}: {e}")
#         break  # Stop if run does not exist or another error occurs

In [4]:
# connect to your Neptune project
project = neptune.init_project(
    "amar-mesic/dna-thesis",
    api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJkOTQ1Njc4MC0yOTcyLTRlMmQtYTMwMy0xOGYxZTAwMmIzZGUifQ==",
)

# fetch runs (maybe filtered by tag or name)
runs_table = project.fetch_runs_table(columns=[
    "sys/name", 
    "meta/experiment", "meta/model", "meta/dataset", "meta/seed", "meta/fold",
    "test/pixel_f1", "test/pixel_precision", "test/pixel_recall",
    "test/allele_f1", "test/allele_precision", "test/allele_recall"
])

[neptune] [info   ] Neptune initialized. Open in the app: https://app.neptune.ai/amar-mesic/dna-thesis/

In [5]:
runs_table

In [6]:
# %pip install -U ipywidgets

# get dataframe
df = runs_table.to_pandas()

# rename to cleaner columns
df = df.rename(columns={
    "meta/experiment": "experiment",
    "meta/model": "model",
    "meta/dataset": "dataset",
    "meta/seed": "seed",
    "meta/fold": "fold",
})

df

Fetching table...: 0 [00:00, ?/s]

,sys/creation_time,sys/id,sys/name,dataset,experiment,fold,model,seed,test/allele_f1,test/allele_precision,test/allele_recall,test/pixel_f1,test/pixel_precision,test/pixel_recall
0,2025-10-03 10:17:49.475,DNAT-648,"DNANet的长-1正真:0正假-考试倍1-预：训练,缩放-种0",PT:Synth+ProvedIt-FT:NFI_R&D,Cross-kit-FineTune,1.0,Amar-DNANet_Advanced,0.0,0.9175,0.9298,0.9055,0.8814,0.8765,0.8863
2,2025-09-27 03:03:32.493,DNAT-646,670+长-1正真:4正假-考试倍4-预：缩放-种0,proved_it_+_synth_1:4,Synth_data-Genotype_aware-SPS,4.0,Amar-DNANet_Advanced-No_pretrain,0.0,0.8481,0.9180,0.7881,0.8616,0.8776,0.8462
3,2025-09-27 03:00:51.053,DNAT-645,670+长-1正真:2正假-考试倍1-预：缩放-种4,proved_it_+_synth_1:2,Synth_data-Genotype_aware-SPS,1.0,Amar-DNANet_Advanced-No_pretrain,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-09-27 02:55:26.484,DNAT-644,670+长-1正真:1正假-考试倍2-预：缩放-种2,proved_it_+_synth_1:1,Synth_data-Genotype_aware-SPS,2.0,Amar-DNANet_Advanced-No_pretrain,2.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-09-27 02:30:01.298,DNAT-643,670+长-1正真:4正假-考试倍2-预：缩放-种2,proved_it_+_synth_1:4,Synth_data-Genotype_aware-SPS,2.0,Amar-DNANet_Advanced-No_pretrain,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2025-07-02 08:10:54.198,DNAT-63,最好U网-100真:0假-早停-lr0.01-用exp调度0.98-第1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,2025-07-01 18:04:27.351,DNAT-62,最好U网-100真:0假-早停-lr0.01-用cyc调度-第1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,2025-07-01 17:07:54.342,DNAT-60,最好U网-100真:0假-早停-lr0.01-用cos调度-第1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,2025-07-01 14:13:53.630,DNAT-54,最好U网-100真:0假-早停-lr0.01-不调度-第1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,2025-07-01 13:20:05.990,DNAT-53,最好U网-100真:0假-早停-lr0.001-不调度-第1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## View specific runs

In [7]:
[1,2,3,4,5][4:]

[5]

In [8]:
# filtered_df = df[(df["experiment"] == "Synth_data-Genotype_aware-SPS") & (df["model"] == "Amar-DNANet_Advanced") & (df["dataset"] == "proved_it_+_synth_1:0")]
filtered_df = df[(df["experiment"] == "Cross-kit-FineTune") & (df["model"] == "Amar-DNANet_Advanced") & (df["dataset"] == "PT:Synth+ProvedIt-FT:NFI_R&D")]

filtered_df

,sys/creation_time,sys/id,sys/name,dataset,experiment,fold,model,seed,test/allele_f1,test/allele_precision,test/allele_recall,test/pixel_f1,test/pixel_precision,test/pixel_recall
0,2025-10-03 10:17:49.475,DNAT-648,"DNANet的长-1正真:0正假-考试倍1-预：训练,缩放-种0",PT:Synth+ProvedIt-FT:NFI_R&D,Cross-kit-FineTune,1.0,Amar-DNANet_Advanced,0.0,0.9175,0.9298,0.9055,0.8814,0.8765,0.8863

In [9]:
list(range(1,3))

[1, 2]

In [10]:
# melt to long format (so you can aggregate all test uniformly)
df_long = df.melt(
    id_vars=["experiment", "model", "dataset", "seed", "fold"],
    value_vars=[
        "test/pixel_f1", "test/pixel_precision", "test/pixel_recall",
        "test/allele_f1", "test/allele_precision", "test/allele_recall"
    ],
    var_name="metric",
    value_name="value"
)
df_long

,experiment,model,dataset,seed,fold,metric,value
0,Cross-kit-FineTune,Amar-DNANet_Advanced,PT:Synth+ProvedIt-FT:NFI_R&D,0.0,1.0,test/pixel_f1,0.8814
1,Synth_data-Genotype_aware-SPS,Amar-DNANet_Advanced-No_pretrain,proved_it_+_synth_1:4,0.0,4.0,test/pixel_f1,0.8616
2,Synth_data-Genotype_aware-SPS,Amar-DNANet_Advanced-No_pretrain,proved_it_+_synth_1:2,4.0,1.0,test/pixel_f1,NaN
3,Synth_data-Genotype_aware-SPS,Amar-DNANet_Advanced-No_pretrain,proved_it_+_synth_1:1,2.0,2.0,test/pixel_f1,NaN
4,Synth_data-Genotype_aware-SPS,Amar-DNANet_Advanced-No_pretrain,proved_it_+_synth_1:4,2.0,2.0,test/pixel_f1,NaN
...,...,...,...,...,...,...,...
2377,NaN,NaN,NaN,NaN,NaN,test/allele_recall,NaN
2378,NaN,NaN,NaN,NaN,NaN,test/allele_recall,NaN
2379,NaN,NaN,NaN,NaN,NaN,test/allele_recall,NaN
2380,NaN,NaN,NaN,NaN,NaN,test/allele_recall,NaN
2381,NaN,NaN,NaN,NaN,NaN,test/allele_recall,NaN

In [11]:
# group + aggregate
summary = (
    df_long
    .groupby(["experiment", "model", "dataset", "metric"])
    .agg(mean=("value", "mean"), std=("value", "std"), 
         min=("value", "min"), max=("value", "max"), n=("value", "count"))
    .reset_index()
)

summary

,experiment,model,dataset,metric,mean,std,min,max,n
0,AT_Baseline,AT_75,proved_it,test/allele_f1,0.758167,0.004325,0.75360,0.76220,3
1,AT_Baseline,AT_75,proved_it,test/allele_precision,0.799100,0.010400,0.78710,0.80550,3
2,AT_Baseline,AT_75,proved_it,test/allele_recall,0.721433,0.012287,0.70810,0.73230,3
3,AT_Baseline,AT_75,proved_it,test/pixel_f1,0.148100,0.002835,0.14490,0.15030,3
4,AT_Baseline,AT_75,proved_it,test/pixel_precision,0.080637,0.001725,0.07868,0.08194,3
...,...,...,...,...,...,...,...,...,...
127,Synth_data-Genotype_aware-SPS-saved,Amar-DNANet_Advanced,proved_it_+_synth_1:0,test/allele_precision,0.914200,NaN,0.91420,0.91420,1
128,Synth_data-Genotype_aware-SPS-saved,Amar-DNANet_Advanced,proved_it_+_synth_1:0,test/allele_recall,0.854000,NaN,0.85400,0.85400,1
129,Synth_data-Genotype_aware-SPS-saved,Amar-DNANet_Advanced,proved_it_+_synth_1:0,test/pixel_f1,0.858700,NaN,0.85870,0.85870,1
130,Synth_data-Genotype_aware-SPS-saved,Amar-DNANet_Advanced,proved_it_+_synth_1:0,test/pixel_precision,0.864000,NaN,0.86400,0.86400,1
131,Synth_data-Genotype_aware-SPS-saved,Amar-DNANet_Advanced,proved_it_+_synth_1:0,test/pixel_recall,0.853500,NaN,0.85350,0.85350,1

In [12]:
def format_row(summary, experiment, model, dataset):
    # metric order
    metrics = [
        "test/allele_f1",
        "test/allele_precision",
        "test/allele_recall",
        "test/pixel_f1",
        "test/pixel_precision",
        "test/pixel_recall",
    ]
    
    # filter for the experiment
    df = summary[
        (summary["experiment"] == experiment)
        & (summary["model"] == model)
        & (summary["dataset"] == dataset)
    ]
    
    values = []
    for m in metrics:
        row = df[df["metric"] == m]
        if row.empty:
            values.append("–")  # no data
        else:
            mean = row["mean"].iloc[0]
            std = row["std"].iloc[0]
            if np.isnan(std) or std == 0:
                values.append(f"{mean:.3f}")
            else:
                # format with 2 sig digits for std
                std_fmt = f"{std:.2g}"
                values.append(f"${mean:.3f}\\pm{std_fmt}$")
    
    return " & ".join(values) + " \\\\"

## Experiment Codes:
* Cross-kit-FineTune
* Genotype_aware-SPS-Standard-DRC

In [13]:
# Example usage
latex_row = format_row(summary, 
                       experiment="Cross-kit-FineTune",
                       model="Amar-DNANet_Advanced",
                       dataset="PT:Synth+ProvedIt-FT:NFI_R&D")

print(latex_row)

0.917 & 0.930 & 0.905 & 0.881 & 0.876 & 0.886 \\

In [15]:
[1,2,3,4,5][2:]

[3, 4, 5]